### ISSUE TITLE
Yapılan ankete dair meta dataların yayınlanması

### ISSUE THREAD

**Issue by lumosmind** [oncekiyazilimci/2020-yazilimci-maaslari#1]
Anket datasındaki **skills** kısmında kullanılan separatorler bazen semantik olarak kendini ifade etse de bazı durumlarda kafa karışıklığına yol açmaktadır.

data içerisinde '**,**' '**;**' '**|**' '**/**'  gibi separatorler yer almakta ancak bunların tam olarak neyi ifade ettiği bilinmeden yapılacak istatistiksel çalışmalar hatalı sonuçlar almamıza sebep olabilir. 
Data içerisindeki separatorlerin anlamalrını yada anket seçeneklerinin meta datasının projeye eklenmesi çok verimli olur.

**Comment by oncekiyazilimci** [comment]
Teşekkürler, meta data dosyası master'a alındı.

**Comment by lumosmind** [comment]
Böyle bir datayı paylaştığınız için ben teşekkür ederim. Ancak data ile uğraştıkça bazı tutarsızlıklar fark ettim. Anketin skills sorusu çoktan seçmeli mi yapıldı yoksa deneğin serberst griş yapabileceği textbox olarak mı giriş yaptırıldı?

**Comment by oncekiyazilimci** [comment]
**position:**
Radio button veya textbox

**skills:**
Checkbox ve textbox

**company:**
Radio button veya textbox

**city:**
Radio button veya textbox

**Comment by lumosmind** [comment]
anladım hocam veriiyi biraz daha temizlemem gerekecek. içerisinde redundant value lar var çünkü.
